# This is the command that will be used
CC = g++ -Wall -Wextra			

# This is the name of the binary ( executable )
Name = hilo

# This is the build parameters
all:
	$(CC) main.cpp  -o $(Name)  -std=c++11

# This is used to "clean up your project"
clean:
	@echo Cleaning up...
	@rm $(Name)
	@echo Done.
